1-Authentication/1-sign-in/SPA/package-lock.json, 1-Authentication/1-sign-in/SPA/package.json, 1-Authentication/2-sign-in-b2c/SPA/package-lock.json, 1-Authentication/2-sign-in-b2c/SPA/package.json, 2-Authorization-I/1-call-graph/SPA/package-lock.json, 2-Authorization-I/1-call-graph/SPA/package.json, 3-Authorization-II/1-call-api/SPA/package-lock.json, 3-Authorization-II/1-call-api/SPA/package.json, 3-Authorization-II/2-call-api-b2c/SPA/package-lock.json, 3-Authorization-II/2-call-api-b2c/SPA/package.json, 4-Deployment/1-deploy-storage/SPA/package-lock.json, 4-Deployment/1-deploy-storage/SPA/package.json, 4-Deployment/2-deploy-static/App/package-lock.json, 4-Deployment/2-deploy-static/App/package.json
* ...
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: **package-update**
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> update msal-react to beta

3-Authorization-II/1-call-api/AppCreationScripts/createdApps.html, 3-Authorization-II/1-call-api/SPA/src/pages/Hello2.jsx, 3-Authorization-II/2-call-api-b2c/README-incremental.md, 3-Authorization-II/2-call-api-b2c/README.md
* This fixes the incorrect instructions for the b2c client app in c3s2
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix c3s2 readme

1-Authentication/1-sign-in/SPA/src/ui.jsx, 1-Authentication/2-sign-in-b2c/SPA/src/ui.jsx, 2-Authorization-I/1-call-graph/SPA/src/components/NavigationBar.jsx, 3-Authorization-II/1-call-api/README-incremental.md, 3-Authorization-II/1-call-api/README.md, 3-Authorization-II/1-call-api/SPA/src/components/NavigationBar.jsx, 3-Authorization-II/2-call-api-b2c/README-incremental.md, 3-Authorization-II/2-call-api-b2c/README.md, 3-Authorization-II/2-call-api-b2c/SPA/src/components/NavigationBar.jsx, 4-Deployment/1-deploy-storage/SPA/src/ui.jsx, 4-Deployment/2-deploy-static/App/src/components/NavigationBar.jsx, 5-AccessControl/1-call-api-roles/SPA/src/components/NavigationBar.jsx, 5-AccessControl/2-call-api-groups/SPA/src/components/NavigationBar.jsx, 6-AdvancedScenarios/1-call-api-obo/SPA/src/components/NavigationBar.jsx
* This adds instructions for setting accessTokenAcceptedVersion to v2
```
[ ] Yes
[ x ] No
```
```
[ x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add accessTokenAcceptedVersion instructions

.github/ISSUE_TEMPLATE.md, 1-Authentication/1-sign-in/README-incremental.md, 1-Authentication/1-sign-in/README.md, 1-Authentication/1-sign-in/SPA/package.json, 1-Authentication/2-sign-in-b2c/README-incremental.md, 1-Authentication/2-sign-in-b2c/README.md, 1-Authentication/2-sign-in-b2c/SPA/package.json, 2-Authorization-I/1-call-graph/README-incremental.md, 2-Authorization-I/1-call-graph/README.md, 2-Authorization-I/1-call-graph/SPA/package.json, 3-Authorization-II/1-call-api/README-incremental.md, 3-Authorization-II/1-call-api/README.md, 3-Authorization-II/1-call-api/SPA/package.json, 3-Authorization-II/2-call-api-b2c/README-incremental.md, 3-Authorization-II/2-call-api-b2c/README.md, 3-Authorization-II/2-call-api-b2c/SPA/package.json, 4-Deployment/1-deploy-storage/SPA/package.json, 4-Deployment/2-deploy-static/App/package.json, 4-Deployment/2-deploy-static/README.md, 5-AccessControl/1-call-api-roles/README.md, 5-AccessControl/1-call-api-roles/SPA/package.json, 5-AccessControl/2-call-api-groups/README.md, 5-AccessControl/2-call-api-groups/SPA/package.json, 6-AdvancedScenarios/1-call-api-obo/SPA/package.json, 6-AdvancedScenarios/2-call-api-pop/README.md, 6-AdvancedScenarios/2-call-api-pop/SPA/package.json, README.md
* bump msal-browser and msal-react
* remove preview tag
* update issue template
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
[ x ] Other... Please describe: package update
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> bump msal, remove preview

2-Authorization-I/1-call-graph/README-incremental.md, 2-Authorization-I/1-call-graph/README.md, 2-Authorization-I/1-call-graph/SPA/package.json, 2-Authorization-I/1-call-graph/SPA/src/authConfig.js, 2-Authorization-I/1-call-graph/SPA/src/graph.js, 2-Authorization-I/1-call-graph/SPA/src/index.js, 2-Authorization-I/1-call-graph/SPA/src/pages/Mails.jsx, 2-Authorization-I/1-call-graph/SPA/src/pages/Profile.jsx, 2-Authorization-I/1-call-graph/SPA/src/pages/Tenant.jsx, 3-Authorization-II/2-call-api-b2c/README-incremental.md, 3-Authorization-II/2-call-api-b2c/README.md
* This PR implements MS Graph JS SDK client with MSAL as custom authentication provider. This is demonstrated in chapter 2.1 call-graph sample.
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ x ] Feature
```
```
git clone https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial.git
cd ms-identity-javascript-react-tutorial
git checkout add-graph-sdk
cd Authorization-I/1-call-graph/SPA
npm install
```
Check [graph.js](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/e8aa8eecfd8471301d66d635a7b900fcb79c64 …
=> demonstrate graph sdk usage

4-Deployment/2-deploy-static/App/src/components/DataDisplay.jsx, 4-Deployment/2-deploy-static/README.md
1. Remove unnecessary step to add Graph User.Read - it is now created by default for every app registration (I tried single and mulit-tenant).
2. Changed display of sensitive data from actual value to ellipsis. 
I'm not sure the step to change the manifest file's value of accessTokenAcceptedVersion is necessary. I didn't do it but the client and API still worked as I expected. What error or lack of functionality should I have seen from not setting it?
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ x] Feature
[ x] Documentation content changes
```
```
cd [repo-name] …
```
=> 4-Deployment\2-deploy-static

.gitignore, 3-Authorization-II/2-call-api-b2c/README-incremental.md, 3-Authorization-II/2-call-api-b2c/README.md, 3-Authorization-II/2-call-api-b2c/SPA/src/authConfig.js
* Correction for Readme steps (chapter 2, sample 2)
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> c3s2 readme correction

2-Authorization-I/1-call-graph/README-incremental.md, 2-Authorization-I/1-call-graph/README.md, 2-Authorization-I/1-call-graph/SPA/src/graph.js
* This PR adds a remark to call-graph samples on using the Graph JavaScript SDK v3.0 AuthCodeMSALBrowserAuthenticationProvider
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
=> add graph sdk v3 notice

6-AdvancedScenarios/3-call-api-acrs/API/app.js, 6-AdvancedScenarios/3-call-api-acrs/SPA/src/fetch.js
* An issue in string methods in the acrs sample was causing the base64 decode to fail. This fixes that.
* Also removed the token caching from the sample
```
[ ] Yes
[ x ] No
```
```
[ x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fix acrs sample encoding issue, remove cache

1-Authentication/1-sign-in/SPA/src/ui.jsx, 1-Authentication/2-sign-in-b2c/SPA/src/ui.jsx, 2-Authorization-I/1-call-graph/SPA/src/components/NavigationBar.jsx, 3-Authorization-II/1-call-api/SPA/src/components/NavigationBar.jsx, 3-Authorization-II/2-call-api-b2c/SPA/src/components/NavigationBar.jsx, 4-Deployment/1-deploy-storage/SPA/src/ui.jsx, 5-AccessControl/1-call-api-roles/SPA/src/components/NavigationBar.jsx, 5-AccessControl/2-call-api-groups/SPA/src/components/NavigationBar.jsx, 6-AdvancedScenarios/1-call-api-obo/SPA/src/components/NavigationBar.jsx, 6-AdvancedScenarios/2-call-api-pop/SPA/src/components/NavigationBar.jsx, 6-AdvancedScenarios/3-call-api-acrs/API/controllers/adminController.js, 6-AdvancedScenarios/3-call-api-acrs/API/models/authContext.js, 6-AdvancedScenarios/3-call-api-acrs/API/utils/routeGuard.js, 6-AdvancedScenarios/3-call-api-acrs/API/views/dashboard.ejs, 6-AdvancedScenarios/3-call-api-acrs/API/views/details.ejs, 6-AdvancedScenarios/3-call-api-acrs/SPA/src/components/NavigationBar.jsx
*  fixes:
1- SPA crashes when the user cancels the login with a popup.
2- Remove button in Auth Context samples used to delete multiple records with the same ID.
3- PUT operation was not supported in Auth Context sample.
4- Default values when creating an Auth Context are incorrect.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> SPA crashes when the user cancels the login with a popup and fixes issues in auth context sample

1-Authentication/1-sign-in/SPA/package-lock.json, 1-Authentication/2-sign-in-b2c/SPA/package-lock.json, 2-Authorization-I/1-call-graph/SPA/package-lock.json, 3-Authorization-II/1-call-api/API/package-lock.json, 3-Authorization-II/1-call-api/SPA/package-lock.json, 3-Authorization-II/2-call-api-b2c/API/package-lock.json, 3-Authorization-II/2-call-api-b2c/SPA/package-lock.json, 4-Deployment/1-deploy-storage/API/package-lock.json, 4-Deployment/1-deploy-storage/SPA/package-lock.json, 5-AccessControl/1-call-api-roles/API/package-lock.json, 5-AccessControl/1-call-api-roles/SPA/package-lock.json, 5-AccessControl/2-call-api-groups/API/package-lock.json, 5-AccessControl/2-call-api-groups/SPA/package-lock.json, 6-AdvancedScenarios/1-call-api-obo/DownstreamAPI/package-lock.json, 6-AdvancedScenarios/1-call-api-obo/MiddletierAPI/package-lock.json, 6-AdvancedScenarios/1-call-api-obo/SPA/package-lock.json, 6-AdvancedScenarios/2-call-api-pop/API/package-lock.json, 6-AdvancedScenarios/2-call-api-pop/README.md, 6-AdvancedScenarios/2-call-api-pop/SPA/package-lock.json, 6-AdvancedScenarios/3-call-api-acrs/API/package-lock.json, 6-AdvancedScenarios/3-call-api-acrs/SPA/package-lock.json
* This P/R addresses the following issues:
1-Updated packages to remove vulnerabilities and security issues in samples.
2-Archived POP sample with a disclaimer not to use the sample
```
[x] Yes
[ ] No
```
```
[x] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> updated packages and archived pop sample

2-Authorization-I/1-call-graph/SPA/package-lock.json, 2-Authorization-I/1-call-graph/SPA/package.json, 2-Authorization-I/1-call-graph/SPA/src/App.jsx, 2-Authorization-I/1-call-graph/SPA/src/components/SessionManager.jsx, 2-Authorization-I/1-call-graph/SPA/src/index.js, 2-Authorization-I/1-call-graph/SPA/src/utils/storageUtils.js
* This PR introduces a new feature to the sample where the SPA application will proactively check the id token expiry time. If the id token has expired, the user will be to reauthenticate silently. 
```
[ x ] Yes
[ ] No
```
```
[ ] Bugfix
[ x ] Feature
```
```
git clone https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial.git
cd  cd  .\2-Authorization-I\1-call-graph\SPA\
git checkout session-managment
npm install 
npm start
```
```
```
* ...
=> Session management feature 

2-Authorization-I/1-call-graph/README-incremental.md, 2-Authorization-I/1-call-graph/README.md, 2-Authorization-I/1-call-graph/SPA/src/fetch.js, 2-Authorization-I/1-call-graph/SPA/src/pages/Contacts.jsx, 2-Authorization-I/1-call-graph/SPA/src/pages/Profile.jsx, 2-Authorization-I/1-call-graph/SPA/src/utils/claimUtils.js, 2-Authorization-I/1-call-graph/SPA/src/utils/storageUtils.js
* fix storage when saving claims challenge 
```
[ x ] Yes
[ ] No
```
```
[ x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> fixed issue with storage

1-Authentication/1-sign-in/SPA/package-lock.json, 1-Authentication/1-sign-in/SPA/package.json
* dependebot PR created a breaking change (react-scripts 4.0.1 ->5.0.1). This PR reverts it.
```
[ ] Yes
[ x ] No
```
```
[ x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> downgrade react-scripts to 4.0.1

2-Authorization-I/1-call-graph/README-incremental.md, 2-Authorization-I/1-call-graph/README.md, 2-Authorization-I/1-call-graph/SPA/package-lock.json, 2-Authorization-I/1-call-graph/SPA/package.json, 2-Authorization-I/1-call-graph/SPA/src/fetch.js, 2-Authorization-I/1-call-graph/SPA/src/graph.js, 2-Authorization-I/1-call-graph/SPA/src/pages/Contacts.jsx, 2-Authorization-I/1-call-graph/SPA/src/pages/Profile.jsx, 2-Authorization-I/1-call-graph/SPA/src/styles/App.css, 2-Authorization-I/1-call-graph/SPA/src/utils/storageUtils.js
* ...
```
[ x ] Yes
[ ] No
```
```
[ ] Bugfix
[ x ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added graph sdk to project

2-Authorization-I/1-call-graph/SPA/src/utils/claimUtils.js, 2-Authorization-I/2-call-arm/SPA/src/utils/claimUtils.js, 3-Authorization-II/1-call-api/SPA/src/utils/claimUtils.js, 5-AccessControl/1-call-api-roles/SPA/src/utils/claimUtils.js, 5-AccessControl/2-call-api-groups/SPA/src/utils/claimUtils.js
* Fix for [issue](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/issues/161)
```
[ x ] Yes
[ ] No
```
```
[ x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fixed issue with ID-token table

1-Authentication/1-sign-in/SPA/src/App.jsx
* Fixes error trying to reference the name of account when no user is signed in. (First example)
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]/1-Authentication/1-sign-in/SPA
npm install
```
```
npm start
browse to http://localhost:3000
sign in
sign out
```
* No error in the console
* Sign-out completes successfully
=> Fix sign out bug

5-AccessControl/1-call-api-roles/SPA/src/utils/claimUtils.js, 5-AccessControl/2-call-api-groups/SPA/src/hooks/useFetchWithMsal.jsx, 5-AccessControl/2-call-api-groups/SPA/src/utils/claimUtils.js
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update claims table to include groups and roles

6-AdvancedScenarios/1-call-api-obo/README.md, 6-AdvancedScenarios/1-call-api-obo/SPA/src/pages/Profile.jsx
* Fix the issue with graph response not showing profile data and update explore the sample section.
```
[ x ] Yes
[ ] No
```
```
[ x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix graph response and update readme

1-Authentication/1-sign-in/README.md, 1-Authentication/2-sign-in-b2c/README.md, 2-Authorization-I/1-call-graph/README.md, 2-Authorization-I/2-call-arm/README.md, 3-Authorization-II/1-call-api/README.md, 3-Authorization-II/2-call-api-b2c/README.md, 4-Deployment/1-deploy-storage/README.md, 4-Deployment/2-deploy-static/README.md, 6-AdvancedScenarios/1-call-api-obo/README.md, 6-AdvancedScenarios/3-call-api-acrs/README.md, 6-AdvancedScenarios/4-sign-in-hybrid/README.md
Linking the code snippets in about the code section to the files the code generated from to improve user readability.
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Adding links to code snippets in about the code section

1-Authentication/2-sign-in-b2c/SPA/src/App.jsx, 1-Authentication/2-sign-in-b2c/SPA/src/utils/claimUtils.js, 3-Authorization-II/2-call-api-b2c/SPA/src/App.jsx, 3-Authorization-II/2-call-api-b2c/SPA/src/hooks/useFetchWithMsal.jsx, 3-Authorization-II/2-call-api-b2c/SPA/src/utils/claimUtils.js, 5-AccessControl/2-call-api-groups/API/package-lock.json, 6-AdvancedScenarios/1-call-api-obo/API/package-lock.json, 6-AdvancedScenarios/3-call-api-acrs/API/package-lock.json
* This PR fixes a string comparison bug in policy comparison utils used in B2C samples
```
[ ] Yes
[ x ] No
```
```
[ x ] Bugfix
[ ] Feature
```
=> fix string comparison bug in b2c samples
